[project]
name = "server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.18.4",
    "fastapi[standard]>=0.136.3",
    "ruff>=0.15.16",
    "sqlalchemy>=2.0.50",
]

[tool.fastapi]
entrypoint = "app.main:app"

[tool.ruff]
exclude = [
    ".git",
    ".ruff_cache",
    ".venv",
    "alembic",
    ".vscode",
]
include = ["*.py"]

line-length = 120
indent-width = 4

output-format = "full"

show-fixes = true
unsafe-fixes = false

target-version = "py314"

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I"]
ignore = []

fixable = ["ALL"]
unfixable = []

preview = true

[tool.ruff.lint.isort]
section-order = [
    "future",
    "standard-library",
    "third-party",
    "first-party",
    "local-folder",
]
combine-as-imports = true
split-on-trailing-comma = true
no-sections = false
lines-after-imports = 2


[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
preview = true

docstring-code-format = true
docstring-code-line-length = "dynamic"
